---
version: "2.1"
services:
  script:
    image: bot-image
    build:
      dockerfile: .docker/Dockerfile.gui
    container_name: bot
    environment:
      - DISPLAY=host.docker.internal:0
    restart: unless-stopped